# Generated by Django 4.1.2 on 2022-10-31 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app_users',
            old_name='conf_pass',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='app_users',
            old_name='fname',
            new_name='Last_name',
        ),
        migrations.RenameField(
            model_name='app_users',
            old_name='lname',
            new_name='confirm_Password',
        ),
    ]
